# Generated by Django 6.0 on 2026-01-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_concert_booking_deadline_festival_booking_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='wedding_details',
        ),
    ]
