# Generated by Django 6.0 on 2026-01-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_booking_wedding_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concert',
        ),
        migrations.RemoveField(
            model_name='concertbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Festival',
        ),
        migrations.RemoveField(
            model_name='festivalbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='sportsregistration',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='sportsregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConcertBooking',
        ),
        migrations.DeleteModel(
            name='FestivalBooking',
        ),
        migrations.DeleteModel(
            name='Fixture',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='SportsRegistration',
        ),
    ]
