# Generated by Django 6.0 on 2026-01-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_concert_remove_concertbooking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_decoration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Decoration',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
