# Generated by Django 6.0 on 2026-02-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_emailotp_user_block_until_user_login_attempts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
