# Generated by Django 6.0 on 2026-02-27 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_delete_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('catering_package', models.CharField(blank=True, max_length=150, null=True)),
                ('catering_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decoration_name', models.CharField(blank=True, max_length=150, null=True)),
                ('decoration_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('performer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('performer_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Advance Paid', 'Advance Paid'), ('Fully Paid', 'Fully Paid')], default='Pending', max_length=20)),
                ('wedding_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_decoration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.decoration')),
            ],
        ),
    ]
