# Generated by Django 6.0 on 2026-02-27 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_decoration_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planner_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('guests', models.IntegerField(default=0)),
                ('location_type', models.CharField(default='Indoor', max_length=50)),
                ('venue_name', models.CharField(blank=True, max_length=200, null=True)),
                ('service_style', models.CharField(default='Standard', max_length=100)),
                ('cuisine_preferences', models.TextField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
