# Generated by Django 6.0 on 2026-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_eventinquiry_jobapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decoration',
            options={'verbose_name_plural': 'Decorations'},
        ),
        migrations.AlterModelOptions(
            name='eventinquiry',
            options={'verbose_name_plural': 'Event Inquiries'},
        ),
        migrations.AddField(
            model_name='decoration',
            name='category',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Sangeet', 'Sangeet'), ('Mehendi', 'Mehendi'), ('Haldi', 'Haldi'), ('Reception', 'Reception'), ('Other', 'Other')], default='Wedding', max_length=50),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
