# Generated by Django 6.0 on 2026-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_decoration_created_at_decoration_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
