# Generated by Django 6.0 on 2026-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_gallery_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
