# Generated by Django 6.0 on 2026-03-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_concert_festival_tournament_concertbooking_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
