# Generated by Django 6.0 on 2026-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
