# Generated by Django 6.0 on 2026-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_concert_is_visible_festival_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('approx_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Wedding Events',
            },
        ),
        migrations.AddField(
            model_name='sportsregistration',
            name='prize_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
