# Generated by Django 6.0 on 2026-03-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_weddingevent_sportsregistration_prize_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='player1_tbd_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='player2_tbd_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
