# Generated by Django 6.0 on 2026-04-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingevent',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='weddingevent',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='weddingevent',
            name='schedule',
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='decoration_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
