# Generated by Django 6.0 on 2026-04-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_weddingevent_faqs_remove_weddingevent_rules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingevent',
            name='approx_price',
        ),
    ]
