# Generated by Django 6.0 on 2026-04-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_weddingevent_approx_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingevent',
            name='decoration_options',
        ),
        migrations.RemoveField(
            model_name='weddingevent',
            name='highlights',
        ),
    ]
