# Generated by Django 6.0 on 2026-04-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_weddingevent_decoration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='category',
            field=models.CharField(default='Wedding', max_length=50),
        ),
    ]
