# Generated by Django 6.0 on 2026-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_decoration_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='artistImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
